### ISSUE TITLE
Multiple possible XSS vulnerabilities

### ISSUE THREAD

**Issue by splitbrain** [turnermm/quickstats#18]
See http://php-grinder.com/project/view/20225 - unfoortunately the scanner timed out, so not all of the code was scanned, but it seems at least in scripts/extended_data.php, input variables are printed out without proper sanitation/escaping. Just from briefly looking over the code it seems to me that I could pass script code in $_POST['date'] and have it orinted out as is in ip_row() and that's just one example.

**Comment by turnermm** [comment]
Think all are fixed but still can't get a result from grinder to check for myself.
