### ISSUE TITLE
PHP Warning: count(): Parameter must be an array or an object that implements Countable in C:\inetpub\wwwroot\dokuwiki\lib\plugins\quickstats\action.php on line 173

### ISSUE THREAD

**Issue by MrsPappi** [turnermm/quickstats#22]
Hello,

I encountered this issue when trying to use the plugin with PHP 7.2.  It appears to be very similar to this issue.  https://bitbucket.org/tormec/acmenu/issues/15/php-72-warning-count-parameter-must-be-an

Thank you for looking into it.

**Comment by turnermm** [comment]
Thanks.  Should be fixed.

**Comment by MrsPappi** [comment]
Thank you so much!!!!!!

FYI - When I click on the admin panel, it's throws a warning.  It sounds like this issue,  http://php.net/manual/en/migration72.deprecated.php.  It seemed like double quotes fixes it all up.

 "PHP Warning: Use of undefined constant general_intro - assumed 'general_intro' (this will throw an Error in a future version of PHP) in C:\inetpub\wwwroot\dokuwiki\lib\plugins\quickstats\admin.php on line 184 PHP Warning: Use of undefined constant intro - assumed 'intro' (this will throw an Error in a future version of PHP) in C:\inetpub\wwwroot\dokuwiki\lib\plugins\quickstats\admin.php on line 199 PHP Warning: Use of undefined constant query - assumed 'query' (this will throw an Error in a future version of PHP) in C:\inetpub\wwwroot\dokuwiki\lib\plugins\quickstats\admin.php on line 223 "

**Comment by turnermm** [comment]
This should be fixed as well/
