### ISSUE TITLE
Remove .gitignore

### ISSUE THREAD

**Issue by shimmtak** [turnermm/quickstats#26]
Please reconsider the necessity of the .gitignore file.
It defines:
```
    scripts/php-inet6_1.0.2/*
    *php-inet6_1.0.2/*
    *php-inet6_1.0.2*
    /scripts/php-inet6_1.0.2/*
```
The `scripts/php-inet6_1.0.2/*` seems work fine and necessary for the plugin.
It is confusing when user manage their site source code by git.

**Comment by turnermm** [comment]
Removed. It was left over from 5 years ago.  One of the scripts in that directory is indeed used by the plugin,  so I'm glad you spotted this.  The other is for (my) information.

**Comment by shimmtak** [comment]
Thank you for your prompt response. I appreciate your nice plugin.
