### ISSUE TITLE
Feature request: Add display of cumulative total #hits to a wiki page

### ISSUE THREAD

**Issue by FilSalustri** [turnermm/quickstats#31]
While the data accumulated by this plugin is useful for various analytic purposes, being able to display - e.g., on the front page of a wiki - the cumulative total hits over all time can be beneficial too. "This wiki has been viewed 1,000,000 times!" sort of thing. 
As an educator, this would be meaningful for my annual reports, and also to indicate my wiki's usefulness over time to my students.
The plugin already seems to collect a cumulative number of hits.
My request is simply to be able to render that on a wiki page.

**Comment by turnermm** [comment]
This is ready now.  Syntax: 
   `~~QUICKSTATS:total~~`

See https://www.dokuwiki.org/plugin:quickstats#example_3 for further comments.

**Comment by FilSalustri** [comment]
Outstanding! Thanks very muc!
