### ISSUE TITLE
Quickstats seems to have become unresponsive

### ISSUE THREAD

**Issue by FilSalustri** [turnermm/quickstats#32]
I'm running the current version of dokuwiki on Ubuntu 18.04.5 LTS.

At some point in the last couple of weeks (I can't be sure exactly when), quickstats seems to have stopped updating.

I use it only in the topmost start page (https://deseng.ryerson.ca/dokuwiki/start). The page starts with `~~NOCACHE~~`, and the invocation is `~~QUICKSTATS:total~~`.

I have no idea how to proceed in diagnosing and fixing this problem. Any assistance would be greatly appreciated.

**Comment by turnermm** [comment]
I think you are referring to no. 3, the rebuild_uip option:
https://www.dokuwiki.org/plugin:quickstats#the_query_form

**Comment by FilSalustri** [comment]
Your advice made sense - unfortunately, it didn't work.

I checked `rebuild_uip` config item, and even opened the admin panel. But after several days, the counter on the front page of the wiki hasn't changed, even though I know many people (my students) have been visiting the wiki.

Can you suggest anything I can try?

**Comment by turnermm** [comment]
Put the `~~NOCACHE~~` macro at the tope of the page.

**Comment by FilSalustri** [comment]
With respect, I already noted that I have `~~NOCACHE~~` at the top of the page, as well as providing the URL to the recalcitrant page.

Ought I insert the raw wikitext of that page here for you review? It's not very long.

**Comment by turnermm** [comment]
Clear out data/cache.  Apart from that, there's nothing I can suggest.  It is working for me.  For instance, go to 
https://www.mturner.org/devel/quick/hits.  The last time I checked it read 1412031.  

If this isn't working, check the web for page hit counters.  Or check for dokuwiki plugins.

**Comment by FilSalustri** [comment]
I think I may have fixed it accidentally (i.e., I don't know why this worked) by turning off the `ajax` flag in quickstats config. Which is to say, since I turned off that flag, the counter is going up again.

Still, I have no idea why it stopped to begin with. But I shall not look a gift horse in the mouth.
